server:
  port: 8080
  
spring:
  application:
    name: apollus-study 
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/apollus-study
    username: postgres
    password: postgres
  jmx:
    enabled: false