server:
  port: 8080
  
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: apollus-study 
  jpa:
    hibernate:
      ddl-auto: none # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/apollus-study #verificar se o nome do banco é o mesmo
    username: postgres
    password: root # verificar senha
  jmx:
    enabled: false